"""
Constants and enumerations for FactGuard backend.
Centralizes magic strings and configuration values.
"""

# Analysis Verdicts
VERDICT_VERIFIED = "Verified"
VERDICT_LIKELY_TRUE = "Likely True"
VERDICT_MIXED_EVIDENCE = "Mixed Evidence"
VERDICT_LIKELY_MISLEADING = "Likely Misleading"
VERDICT_UNVERIFIED = "Unverified"

VALID_VERDICTS = {
    VERDICT_VERIFIED,
    VERDICT_LIKELY_TRUE,
    VERDICT_MIXED_EVIDENCE,
    VERDICT_LIKELY_MISLEADING,
    VERDICT_UNVERIFIED,
}

# Confidence Levels
CONFIDENCE_LOW = "Low"
CONFIDENCE_MEDIUM = "Medium"
CONFIDENCE_HIGH = "High"

VALID_CONFIDENCES = {
    CONFIDENCE_LOW,
    CONFIDENCE_MEDIUM,
    CONFIDENCE_HIGH,
}

# Source Stances
STANCE_SUPPORTS = "supports"
STANCE_CONTRADICTS = "contradicts"
STANCE_NEUTRAL = "neutral"

VALID_STANCES = {
    STANCE_SUPPORTS,
    STANCE_CONTRADICTS,
    STANCE_NEUTRAL,
}

# Claim Status
STATUS_PROCESSING = "processing"
STATUS_DONE = "done"
STATUS_FAILED = "failed"

VALID_STATUSES = {
    STATUS_PROCESSING,
    STATUS_DONE,
    STATUS_FAILED,
}

# API Response Status Codes
HTTP_OK = 200
HTTP_CREATED = 201
HTTP_BAD_REQUEST = 400
HTTP_NOT_FOUND = 404
HTTP_UNPROCESSABLE_ENTITY = 422
HTTP_INTERNAL_SERVER_ERROR = 500
HTTP_SERVICE_UNAVAILABLE = 503

# Error Codes
ERROR_VALIDATION = "VALIDATION_ERROR"
ERROR_CLAIM_NOT_FOUND = "CLAIM_NOT_FOUND"
ERROR_ANALYSIS_FAILED = "ANALYSIS_FAILED"
ERROR_GEMINI_API = "GEMINI_API_ERROR"
ERROR_DATABASE = "DATABASE_ERROR"
ERROR_CONFIG = "CONFIGURATION_ERROR"
ERROR_INTERNAL = "INTERNAL_ERROR"

# Database Table Names
TABLE_CLAIMS = "claims"
TABLE_RESULTS = "results"
TABLE_SOURCES = "sources"

# Cache Configuration
CACHE_TTL_SHORT = 300  # 5 minutes
CACHE_TTL_MEDIUM = 3600  # 1 hour
CACHE_TTL_LONG = 86400  # 1 day

# Rate Limiting
RATE_LIMIT_VERIFY_REQUESTS = 10
RATE_LIMIT_VERIFY_PERIOD = 60  # seconds

# Validation Constraints
MIN_CLAIM_LENGTH = 5
MAX_CLAIM_LENGTH = 2000
MIN_SUMMARY_LENGTH = 10
MAX_SUMMARY_LENGTH = 500
MAX_SOURCES = 20

# Default Values
DEFAULT_RELEVANCE_SCORE = 5
DEFAULT_SOURCE_COUNT = 0
DEFAULT_LIMIT = 10
DEFAULT_OFFSET = 0

# Gemini Model Configuration
GEMINI_MODEL_NAME = "gemini-2.5-flash"
GEMINI_MAX_RETRIES = 3
