'use client';

import { useState } from 'react';
import { Download } from 'lucide-react';
import type { ProductListing, ProductVariant } from '@/types';

interface PriceShareCardProps {
  jobId: string;
  product: string;
  listings: ProductListing[];
  variants: ProductVariant[];
}

function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#x27;');
}

export function PriceShareCard({
  jobId,
  product,
  listings,
  variants,
}: PriceShareCardProps) {
  const [copied, setCopied] = useState(false);

  const url = `${window.location.origin}/price-result/${jobId}`;

  async function copy() {
    try {
      await navigator.clipboard.writeText(url);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      const el = document.getElementById('price-share-url');
      if (el) {
        const range = document.createRange();
        range.selectNodeContents(el);
        window.getSelection()?.removeAllRanges();
        window.getSelection()?.addRange(range);
        document.execCommand('copy');
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      }
    }
  }

  function download() {
    const prod = esc(product);

    const trustIcon = (t: string) =>
      t === 'High' ? '🟢' : t === 'Medium' ? '🟡' : '🔴';

    const listingRows = listings
      .map(
        (l) => `
      <tr>
        <td style="padding:8px;border:1px solid #ddd">${trustIcon(l.trustLevel)} ${esc(l.merchant)}</td>
        <td style="padding:8px;border:1px solid #ddd">${esc(l.title)}</td>
        <td style="padding:8px;border:1px solid #ddd">${l.price != null ? '$' + l.price.toFixed(2) : '—'}</td>
        <td style="padding:8px;border:1px solid #ddd">${esc(l.condition || 'New')}</td>
        <td style="padding:8px;border:1px solid #ddd"><a href="${esc(l.url)}" style="color:#6366f1">Link</a></td>
      </tr>`
      )
      .join('');

    const variantRows = variants
      .map(
        (v) => `
      <tr>
        <td style="padding:8px;border:1px solid #ddd">${esc(v.model)}</td>
        <td style="padding:8px;border:1px solid #ddd">${esc(v.specs || '')}</td>
        <td style="padding:8px;border:1px solid #ddd">${esc(v.priceRange)}</td>
      </tr>`
      )
      .join('');

    const html = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>FactGuard Price Report</title></head>
<body style="font-family:sans-serif;max-width:800px;margin:40px auto;padding:20px;color:#1e293b">
  <h1 style="color:#6366f1">FactGuard Price Report</h1>
  <p style="color:#64748b;font-size:14px">Price comparison · ${new Date().toLocaleDateString()}</p>

  <h2>Product</h2>
  <p style="font-size:18px;background:#f8fafc;padding:16px;border-radius:8px">${prod}</p>

  <h2>Price Comparison (${listings.length} listings)</h2>
  <table style="width:100%;border-collapse:collapse;font-size:13px">
    <thead><tr style="background:#f1f5f9">
      <th style="padding:8px;border:1px solid #ddd;text-align:left">Merchant</th>
      <th style="padding:8px;border:1px solid #ddd;text-align:left">Product</th>
      <th style="padding:8px;border:1px solid #ddd;text-align:right">Price</th>
      <th style="padding:8px;border:1px solid #ddd;text-align:center">Condition</th>
      <th style="padding:8px;border:1px solid #ddd;text-align:center">Link</th>
    </tr></thead>
    <tbody>${listingRows}</tbody>
  </table>

  ${variantRows ? `<h2>Other Models</h2>
  <table style="width:100%;border-collapse:collapse;font-size:13px">
    <thead><tr style="background:#f1f5f9">
      <th style="padding:8px;border:1px solid #ddd;text-align:left">Model</th>
      <th style="padding:8px;border:1px solid #ddd;text-align:left">Specs</th>
      <th style="padding:8px;border:1px solid #ddd;text-align:right">Price Range</th>
    </tr></thead>
    <tbody>${variantRows}</tbody>
  </table>` : ''}

  <p style="margin-top:32px;font-size:12px;color:#94a3b8">Generated by FactGuard</p>
</body></html>`;

    const blob = new Blob([html], { type: 'text/html' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `factguard-price-${prod.slice(0, 40).replace(/\s+/g, '-').toLowerCase() || 'report'}.html`;
    a.click();
    URL.revokeObjectURL(a.href);
  }

  return (
    <div className="flex items-center gap-3 pt-4 border-t border-[var(--card-border)]">
      <div className="flex-1 min-w-0">
        <p
          className="text-xs text-[var(--muted-foreground)] font-mono truncate"
          id="price-share-url"
        >
          {url || '—'}
        </p>
      </div>

      <button
        onClick={copy}
        disabled={!url}
        className="shrink-0 text-xs font-semibold text-[var(--accent)] hover:text-[var(--accent-hover)] disabled:opacity-40 transition-colors underline-offset-2 hover:underline"
      >
        {copied ? 'Copied ✓' : 'Copy link'}
      </button>

      <button
        onClick={download}
        className="flex items-center gap-1.5 shrink-0 text-xs font-semibold text-[var(--accent)] hover:text-[var(--accent-hover)] transition-colors px-3 py-1.5 rounded-lg border border-[var(--card-border)] hover:bg-[var(--muted)]"
      >
        <Download className="size-3" />
        Download
      </button>
    </div>
  );
}
