VERDICT_VERIFIED = "Verified"
VERDICT_LIKELY_TRUE = "Likely True"
VERDICT_MIXED_EVIDENCE = "Mixed Evidence"
VERDICT_LIKELY_MISLEADING = "Likely Misleading"
VERDICT_UNVERIFIED = "Unverified"

VALID_VERDICTS = {
    VERDICT_VERIFIED,
    VERDICT_LIKELY_TRUE,
    VERDICT_MIXED_EVIDENCE,
    VERDICT_LIKELY_MISLEADING,
    VERDICT_UNVERIFIED,
}

CONFIDENCE_LOW = "Low"
CONFIDENCE_MEDIUM = "Medium"
CONFIDENCE_HIGH = "High"

VALID_CONFIDENCES = {
    CONFIDENCE_LOW,
    CONFIDENCE_MEDIUM,
    CONFIDENCE_HIGH,
}

STANCE_SUPPORTS = "supports"
STANCE_CONTRADICTS = "contradicts"
STANCE_NEUTRAL = "neutral"

VALID_STANCES = {
    STANCE_SUPPORTS,
    STANCE_CONTRADICTS,
    STANCE_NEUTRAL,
}

STATUS_PENDING = "pending"
STATUS_PROCESSING = "processing"
STATUS_DONE = "done"
STATUS_ERROR = "error"

VALID_STATUSES = {
    STATUS_PENDING,
    STATUS_PROCESSING,
    STATUS_DONE,
    STATUS_ERROR,
}

PRICING_STATUSES = {STATUS_PENDING, STATUS_PROCESSING, STATUS_DONE, STATUS_ERROR}  # same as claims

PRICING_PROGRESS_SEARCHING = "Searching for prices..."
PRICING_PROGRESS_ANALYZING = "Analyzing product data..."
PRICING_PROGRESS_SAVING = "Saving results..."

ERROR_VALIDATION = "VALIDATION_ERROR"
ERROR_CLAIM_NOT_FOUND = "CLAIM_NOT_FOUND"
ERROR_ANALYSIS_FAILED = "ANALYSIS_FAILED"
ERROR_GEMINI_API = "GEMINI_API_ERROR"
ERROR_DATABASE = "DATABASE_ERROR"
ERROR_CONFIG = "CONFIGURATION_ERROR"
ERROR_INTERNAL = "INTERNAL_ERROR"

# Track types
TRACK_GTM = "gtm"
TRACK_FINANCE = "finance"
TRACK_SECURITY = "security"
TRACK_CART = "cart"

VALID_TRACKS = {TRACK_GTM, TRACK_FINANCE, TRACK_SECURITY, TRACK_CART}

# Threat types
THREAT_BRAND = "brand"
THREAT_REGULATORY = "regulatory"
THREAT_VENDOR = "vendor"
THREAT_DISINFORMATION = "disinformation"
THREAT_GENERAL = "general"

VALID_THREAT_TYPES = {
    THREAT_BRAND,
    THREAT_REGULATORY,
    THREAT_VENDOR,
    THREAT_DISINFORMATION,
    THREAT_GENERAL,
}

# Severity levels
SEVERITY_LOW = "low"
SEVERITY_MEDIUM = "medium"
SEVERITY_HIGH = "high"
SEVERITY_CRITICAL = "critical"

VALID_SEVERITIES = {SEVERITY_LOW, SEVERITY_MEDIUM, SEVERITY_HIGH, SEVERITY_CRITICAL}

# Alert statuses
ALERT_NEW = "new"
ALERT_ACKNOWLEDGED = "acknowledged"
ALERT_INVESTIGATING = "investigating"
ALERT_RESOLVED = "resolved"
ALERT_DISMISSED = "dismissed"

VALID_ALERT_STATUSES = {
    ALERT_NEW,
    ALERT_ACKNOWLEDGED,
    ALERT_INVESTIGATING,
    ALERT_RESOLVED,
    ALERT_DISMISSED,
}
